name: Metrics
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          filename: metrics.svg
          committer_branch: metrics
          config_plugins_languages: yes
          config_plugins_achievements: yes
          config_plugins_stars: yes
          config_plugins_wakatime: yes
          config_plugins_wakatime_sections: all
          config_plugins_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
