name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *"  # Génère toutes les 6 heures
  workflow_dispatch:        # Permet de lancer manuellement
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}      # Ton PAT avec droit "repo"
          user: morchid65
          template: classic
          base: header, activity, community, repositories, metadata
          filename: github-metrics.svg
