name: Metrics
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: github
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          filename: metrics.svg
          committer_branch: gh-pages
