name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          config_plugins_followup: yes
          config_plugins_lines: yes
          config_plugins_wakatime: yes
          config_plugins_wakatime_sections: all
          config_plugins_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          filename: github-metrics.svg
