name: Metrics
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          filename: metrics.svg
          committer_branch: main

          # Active les plugins pour les différents graphiques
          plugin_activity: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_stars: yes
          plugin_wakatime: yes
          
          # Options pour WakaTime
          plugin_wakatime_sections: all
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
