name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          output: github-metrics.svg
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          plugins_followup: yes
          plugins_lines: yes
          plugins_wakatime: yes
          plugins_wakatime_sections: all
          plugins_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugins_notable_projects: yes
          plugins_notable_projects_projects: morchid65/projet-refonte-site
