name: Metrics
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          filename: metrics.svg
          committer_branch: main

          # Configuration des plugins
          plugins:
            # Active le plugin d'activité pour les graphiques horaires
            activity: yes
            languages: yes
            achievements: yes
            stars: yes
            wakatime: yes

          # Options pour les plugins
          plugin_wakatime:
            sections: all
            token: ${{ secrets.WAKATIME_TOKEN }}
