name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: morchid65
          template: classic
          base: header, activity, community, repositories, metadata
          filename: github-metrics.svg
          plugin_languages: yes
          plugin_achievements: yes
          plugin_stars: yes
